// SPDX-FileCopyrightText: 2021 Open Networking Foundation <info@opennetworking.org>
// Copyright 2019 free5GC.org
//
// SPDX-License-Identifier: Apache-2.0

/*
 * Nsmf_PDUSession
 *
 * SMF PDU Session Service
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package main

import (
	"fmt"
	"os"

	"github.com/omec-project/smf/logger"
	"github.com/omec-project/smf/service"
	"github.com/urfave/cli"
	"go.uber.org/zap"
)

var SMF = &service.SMF{}

var appLog *zap.SugaredLogger

func init() {
	appLog = logger.AppLog
}

func main() {
	app := cli.NewApp()
	app.Name = "smf"
	appLog.Infoln(app.Name)
	app.Usage = "-cfg common configuration file -smfcfg smf_configuration_file"
	app.Action = action
	app.Flags = SMF.GetCliCmd()

	if err := app.Run(os.Args); err != nil {
		appLog.Errorf("SMF Run error: %v", err)
	}
}

func action(c *cli.Context) error {
	if err := SMF.Initialize(c); err != nil {
		logger.CfgLog.Errorf("%+v", err)
		return fmt.Errorf("failed to initialize")
	}

	SMF.Start()

	return nil
}
