/*
 * Nsmf_PDUSession
 *
 * SMF PDU Session Service
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package pdusession

import (
	"free5gc/lib/http_wrapper"
	"free5gc/lib/openapi"
	"free5gc/lib/openapi/models"
	"free5gc/src/smf/logger"
	"free5gc/src/smf/producer"
	"github.com/gin-gonic/gin"
	"net/http"
	"strings"
	smf_context "free5gc/src/smf/context"
	stats "free5gc/src/smf/metrics"
	"free5gc/lib/msgtypes"
)

// HTTPPostSmContexts - Create SM Context
func HTTPPostSmContexts(c *gin.Context) {
	logger.PduSessLog.Info("Recieve Create SM Context Request")
	var request models.PostSmContextsRequest
	stats.IncrementN11MsgStats(smf_context.SMF_Self().NfInstanceID, msgtypes.NsmfPDUSessionCreateSmContext, "In", "", "")

	request.JsonData = new(models.SmContextCreateData)

	s := strings.Split(c.GetHeader("Content-Type"), ";")
	var err error
	switch s[0] {
	case "application/json":
		err = c.ShouldBindJSON(request.JsonData)
	case "multipart/related":
		err = c.ShouldBindWith(&request, openapi.MultipartRelatedBinding{})
	}

	if err != nil {
		problemDetail := "[Request Body] " + err.Error()
		rsp := models.ProblemDetails{
			Title:  "Malformed request syntax",
			Status: http.StatusBadRequest,
			Detail: problemDetail,
		}
		stats.IncrementN11MsgStats(smf_context.SMF_Self().NfInstanceID, msgtypes.NsmfPDUSessionCreateSmContext, "Out", http.StatusText(http.StatusBadRequest), "Malformed")
		logger.PduSessLog.Errorln(problemDetail)
		c.JSON(http.StatusBadRequest, rsp)
		return
	}

	req := http_wrapper.NewRequest(c.Request, request)
	HTTPResponse, errStr := producer.HandlePDUSessionSMContextCreate(req.Body.(models.PostSmContextsRequest))
	//Http Response to AMF
	for key, val := range HTTPResponse.Header {
		c.Header(key, val[0])
	}
	stats.IncrementN11MsgStats(smf_context.SMF_Self().NfInstanceID, msgtypes.NsmfPDUSessionCreateSmContext, "Out", http.StatusText(HTTPResponse.Status), errStr)
	switch HTTPResponse.Status {
	case http.StatusCreated,
		http.StatusBadRequest,
		http.StatusForbidden,
		http.StatusNotFound,
		http.StatusInternalServerError,
		http.StatusServiceUnavailable,
		http.StatusGatewayTimeout:
		c.Render(HTTPResponse.Status, openapi.MultipartRelatedRender{Data: HTTPResponse.Body})
	default:
		c.JSON(HTTPResponse.Status, HTTPResponse.Body)
	}
}
