// SPDX-FileCopyrightText: 2021 Open Networking Foundation <info@opennetworking.org>
//
// SPDX-License-Identifier: Apache-2.0
// SPDX-License-Identifier: LicenseRef-ONF-Member-Only-1.0

/*
 * Nsmf_PDUSession
 *
 * SMF PDU Session Service
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package pdusession

import (
	"net/http"
	"strings"

	"github.com/gin-gonic/gin"

	"github.com/free5gc/http_wrapper"
	"github.com/free5gc/openapi"
	"github.com/free5gc/openapi/models"
	"github.com/free5gc/smf/fsm"
	"github.com/free5gc/smf/logger"
	"github.com/free5gc/smf/transaction"

	smf_context "github.com/free5gc/smf/context"
	stats "github.com/free5gc/smf/metrics"
	"github.com/free5gc/smf/msgtypes/svcmsgtypes"
)

// HTTPPostSmContexts - Create SM Context
func HTTPPostSmContexts(c *gin.Context) {
	logger.PduSessLog.Info("Recieve Create SM Context Request")
	var request models.PostSmContextsRequest
	stats.IncrementN11MsgStats(smf_context.SMF_Self().NfInstanceID, string(svcmsgtypes.NsmfPDUSessionCreateSmContext), "In", "", "")

	request.JsonData = new(models.SmContextCreateData)

	s := strings.Split(c.GetHeader("Content-Type"), ";")
	var err error
	switch s[0] {
	case "application/json":
		err = c.ShouldBindJSON(request.JsonData)
	case "multipart/related":
		err = c.ShouldBindWith(&request, openapi.MultipartRelatedBinding{})
	}

	if err != nil {
		problemDetail := "[Request Body] " + err.Error()
		rsp := models.ProblemDetails{
			Title:  "Malformed request syntax",
			Status: http.StatusBadRequest,
			Detail: problemDetail,
		}
		stats.IncrementN11MsgStats(smf_context.SMF_Self().NfInstanceID, string(svcmsgtypes.NsmfPDUSessionCreateSmContext), "Out", http.StatusText(http.StatusBadRequest), "Malformed")
		logger.PduSessLog.Errorln(problemDetail)
		c.JSON(http.StatusBadRequest, rsp)
		return
	}

	req := http_wrapper.NewRequest(c.Request, request)
	txn := transaction.NewTransaction(req.Body.(models.PostSmContextsRequest), nil, svcmsgtypes.SmfMsgType(svcmsgtypes.NsmfPDUSessionCreate))

	go txn.StartTxnLifeCycle(fsm.SmfTxnFsmHandle)
	<-txn.Status //wait for txn to complete at SMF
	HTTPResponse := txn.Rsp.(*http_wrapper.Response)
	smContext := txn.Ctxt.(*smf_context.SMContext)
	errStr := ""
	if txn.Err != nil {
		errStr = txn.Err.Error()
	}

	//HTTPResponse, errStr, smContext := producer.HandlePDUSessionSMContextCreate(req.Body.(models.PostSmContextsRequest))
	//Http Response to AMF

	for key, val := range HTTPResponse.Header {
		c.Header(key, val[0])
	}
	stats.IncrementN11MsgStats(smf_context.SMF_Self().NfInstanceID, string(svcmsgtypes.NsmfPDUSessionCreateSmContext), "Out", http.StatusText(HTTPResponse.Status), errStr)
	switch HTTPResponse.Status {
	case http.StatusCreated,
		http.StatusBadRequest,
		http.StatusForbidden,
		http.StatusNotFound,
		http.StatusInternalServerError,
		http.StatusServiceUnavailable,
		http.StatusGatewayTimeout:
		c.Render(HTTPResponse.Status, openapi.MultipartRelatedRender{Data: HTTPResponse.Body})
	default:
		c.JSON(HTTPResponse.Status, HTTPResponse.Body)
	}

	go func(smContext *smf_context.SMContext) {

		var txn *transaction.Transaction
		if HTTPResponse.Status == http.StatusCreated {
			txn = transaction.NewTransaction(nil, nil, svcmsgtypes.SmfMsgType(svcmsgtypes.SmEventPfcpSessCreate))
			txn.Ctxt = smContext
			go txn.StartTxnLifeCycle(fsm.SmfTxnFsmHandle)
			<-txn.Status
		} else {
			smf_context.RemoveSMContext(smContext.Ref)
		}

		//smContext.SMLock.Lock()
		//defer smContext.SMLock.Unlock()
		//Send delayed PFCP Sess Establish if ctxt created
		/*
			if HTTPResponse.Status == http.StatusCreated {
				producer.SendPFCPRules(smContext)
			} else if smContext != nil {
				//release ctxt incase of failure
				smf_context.RemoveSMContext(smContext.Ref)
			}
		*/
	}(smContext)
}
