// Copyright (c) 2026 Intel Corporation
// SPDX-License-Identifier: Apache-2.0

/*
Nsmf_PDUSession

SMF PDU Session Service.
© 2024, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).
All rights reserved.

API version: 1.3.0-alpha.7

Authors: Aether SD-Core team
Contact: dev@lists.aetherproject.org

Generated by: OpenAPI Generator (https://openapi-generator.tech)
*/

package pdusession

import (
	"github.com/gin-gonic/gin"
	"github.com/omec-project/smf/logger"
)

// Post /:$request.body#/ismfPduSessionUri
// Notify Status
func HTTPNotifyStatusIsmf(c *gin.Context) {
	detail := "Handle Post /:$request.body#/ismfPduSessionUri is not implemented"
	logger.PduSessLog.Warnln(detail)
	writeNotImplementedProblem(c, detail)
}
