// Copyright (c) 2026 Intel Corporation
// SPDX-License-Identifier: Apache-2.0

/*
Nsmf_PDUSession

SMF PDU Session Service.
© 2024, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).
All rights reserved.

API version: 1.3.0-alpha.7

Authors: Aether SD-Core team
Contact: dev@lists.aetherproject.org

Generated by: OpenAPI Generator (https://openapi-generator.tech)
*/

package pdusession

import (
	"net/http"
	"strings"

	"github.com/gin-gonic/gin"
	"github.com/omec-project/openapi/v2"
	"github.com/omec-project/openapi/v2/models"
	"github.com/omec-project/openapi/v2/utils"
	smf_context "github.com/omec-project/smf/context"
	"github.com/omec-project/smf/fsm"
	"github.com/omec-project/smf/logger"
	stats "github.com/omec-project/smf/metrics"
	"github.com/omec-project/smf/msgtypes/svcmsgtypes"
	"github.com/omec-project/smf/transaction"
	smfutil "github.com/omec-project/smf/util"
	"github.com/omec-project/util/httpwrapper"
	mi "github.com/omec-project/util/metricinfo"
)

var (
	multipartRelated string = "multipart/related"
	multipartForm    string = "multipart/form-data"
	applicationJson  string = "application/json"
)

func shouldRenderUpdateSmContextMultipart(body any) bool {
	switch response := body.(type) {
	case models.UpdateSmContext200Response:
		return response.HasBinaryDataN1SmMessage() || response.HasBinaryDataN2SmInformation()
	case *models.UpdateSmContext200Response:
		return response != nil && (response.HasBinaryDataN1SmMessage() || response.HasBinaryDataN2SmInformation())
	case models.UpdateSmContext400Response:
		return response.HasBinaryDataN1SmMessage() || response.HasBinaryDataN2SmInformation()
	case *models.UpdateSmContext400Response:
		return response != nil && (response.HasBinaryDataN1SmMessage() || response.HasBinaryDataN2SmInformation())
	default:
		return false
	}
}

func renderUpdateSmContextResponse(c *gin.Context, response *httpwrapper.Response) {
	if response.Status < http.StatusMultipleChoices || shouldRenderUpdateSmContextMultipart(response.Body) {
		c.Render(response.Status, openapi.MultipartRelatedRender{Data: response.Body})
		smfutil.CleanupMultipartTempFiles(response.Body)
		return
	}

	c.JSON(response.Status, response.Body)
}

// Post /sm-contexts/:smContextRef/release
// Release SM Context
func HTTPReleaseSmContext(c *gin.Context) {
	logger.PduSessLog.Infoln("Handle Post /sm-contexts/:smContextRef/release")
	var err error
	stats.IncrementN11MsgStats(smf_context.SMF_Self().NfInstanceID, string(svcmsgtypes.ReleaseSmContext), "In", "", "")
	err = stats.PublishMsgEvent(mi.Smf_msg_type_pdu_sess_release_req)
	if err != nil {
		logger.PduSessLog.Errorf("error: %v", err)
		return
	}

	var request models.ReleaseSmContextRequest
	request.JsonData = models.NewSmContextReleaseData()

	s := strings.Split(c.GetHeader("Content-Type"), ";")
	switch s[0] {
	case applicationJson:
		err = c.ShouldBindJSON(request.JsonData)
	case multipartRelated, multipartForm:
		err = c.ShouldBindWith(&request, openapi.MultipartRelatedBinding{})
	default:
		problemDetail := "[Request Body] unsupported Content-Type: " + c.GetHeader("Content-Type")
		rsp := utils.ProblemDetailsSystemFailure(problemDetail)
		logger.PduSessLog.Errorln(problemDetail)
		c.JSON(http.StatusUnsupportedMediaType, rsp)
		stats.IncrementN11MsgStats(smf_context.SMF_Self().NfInstanceID, string(svcmsgtypes.ReleaseSmContext), "Out", http.StatusText(http.StatusUnsupportedMediaType), "UnsupportedMediaType")
		return
	}
	defer smfutil.CleanupMultipartTempFiles(request)
	if err != nil {
		logger.PduSessLog.Errorln(err)
		problemDetail := "[Request Body] " + err.Error()
		rsp := utils.ProblemDetailsMalformedRequestSyntax(problemDetail)
		logger.PduSessLog.Errorln(problemDetail)
		c.JSON(http.StatusBadRequest, rsp)
		stats.IncrementN11MsgStats(smf_context.SMF_Self().NfInstanceID, string(svcmsgtypes.ReleaseSmContext), "Out", http.StatusText(http.StatusBadRequest), "Malformed")
		return
	}

	req := httpwrapper.NewRequest(c.Request, request)
	req.Params["smContextRef"] = c.Params.ByName("smContextRef")

	smContextRef := req.Params["smContextRef"]
	txn := transaction.NewTransaction(req.Body.(models.ReleaseSmContextRequest), nil, svcmsgtypes.ReleaseSmContext)
	txn.CtxtKey = smContextRef
	go txn.StartTxnLifeCycle(fsm.SmfTxnFsmHandle)
	<-txn.Status

	stats.IncrementN11MsgStats(smf_context.SMF_Self().NfInstanceID, string(svcmsgtypes.ReleaseSmContext), "Out", http.StatusText(http.StatusNoContent), "")
	c.Status(http.StatusNoContent)
}

// Post /sm-contexts/:smContextRef/retrieve
// Retrieve SM Context
func HTTPRetrieveSmContext(c *gin.Context) {
	detail := "Handle Post /sm-contexts/:smContextRef/retrieve is not implemented"
	logger.PduSessLog.Warnln(detail)
	writeNotImplementedProblem(c, detail)
}

// Post /sm-contexts/:smContextRef/send-mo-data
// Send MO Data
func HTTPSendMoData(c *gin.Context) {
	detail := "Handle Post /sm-contexts/:smContextRef/send-mo-data is not implemented"
	logger.PduSessLog.Warnln(detail)
	writeNotImplementedProblem(c, detail)
}

// Post /sm-contexts/:smContextRef/modify
// Update SM Context
func HTTPUpdateSmContext(c *gin.Context) {
	logger.PduSessLog.Infoln("Handle Post /sm-contexts/:smContextRef/modify")
	var err error
	stats.IncrementN11MsgStats(smf_context.SMF_Self().NfInstanceID, string(svcmsgtypes.UpdateSmContext), "In", "", "")
	err = stats.PublishMsgEvent(mi.Smf_msg_type_pdu_sess_modify_req)
	if err != nil {
		logger.PduSessLog.Errorf("error: %v", err)
		return
	}

	var request models.UpdateSmContextRequest
	request.JsonData = models.NewSmContextUpdateData()

	s := strings.Split(c.GetHeader("Content-Type"), ";")
	switch s[0] {
	case applicationJson:
		err = c.ShouldBindJSON(request.JsonData)
	case multipartRelated, multipartForm:
		err = c.ShouldBindWith(&request, openapi.MultipartRelatedBinding{})
	default:
		problemDetail := "[Request Body] unsupported Content-Type: " + c.GetHeader("Content-Type")
		rsp := utils.ProblemDetailsSystemFailure(problemDetail)
		logger.PduSessLog.Errorln(problemDetail)
		c.JSON(http.StatusUnsupportedMediaType, rsp)
		stats.IncrementN11MsgStats(smf_context.SMF_Self().NfInstanceID, string(svcmsgtypes.UpdateSmContext), "Out", http.StatusText(http.StatusUnsupportedMediaType), "UnsupportedMediaType")
		return
	}
	if err != nil {
		problemDetail := "[Request Body] " + err.Error()
		rsp := utils.ProblemDetailsMalformedRequestSyntax(problemDetail)
		logger.PduSessLog.Errorln(problemDetail)
		c.JSON(http.StatusBadRequest, rsp)

		stats.IncrementN11MsgStats(smf_context.SMF_Self().NfInstanceID, string(svcmsgtypes.UpdateSmContext), "Out", http.StatusText(http.StatusBadRequest), "Malformed")
		logger.PduSessLog.Errorln(err)
		return
	}
	defer smfutil.CleanupMultipartTempFiles(request)

	req := httpwrapper.NewRequest(c.Request, request)
	req.Params["smContextRef"] = c.Params.ByName("smContextRef")

	smContextRef := req.Params["smContextRef"]

	txn := transaction.NewTransaction(req.Body.(models.UpdateSmContextRequest), nil, svcmsgtypes.UpdateSmContext)
	txn.CtxtKey = smContextRef
	go txn.StartTxnLifeCycle(fsm.SmfTxnFsmHandle)
	<-txn.Status
	HTTPResponse, ok := txn.Rsp.(*httpwrapper.Response)
	if !ok || HTTPResponse == nil {
		logger.PduSessLog.Errorf("update SM Context transaction finished without HTTP response: err=%v", txn.Err)
		problemDetails := models.NewProblemDetails()
		problemDetails.SetStatus(http.StatusInternalServerError)
		problemDetails.SetCause("SYSTEM_FAILURE")
		problemDetails.SetDetail("SM Context update transaction failed")
		c.JSON(http.StatusInternalServerError, problemDetails)
		return
	}

	stats.IncrementN11MsgStats(smf_context.SMF_Self().NfInstanceID, string(svcmsgtypes.UpdateSmContext), "Out", http.StatusText(HTTPResponse.Status), "")

	renderUpdateSmContextResponse(c, HTTPResponse)
}
