// Copyright (c) 2026 Intel Corporation
// SPDX-License-Identifier: Apache-2.0

/*
Nsmf_PDUSession

SMF PDU Session Service.
© 2024, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).
All rights reserved.

API version: 1.3.0-alpha.7

Authors: Aether SD-Core team
Contact: dev@lists.aetherproject.org

Generated by: OpenAPI Generator (https://openapi-generator.tech)
*/

package pdusession

import (
	"net/http"
	"strings"

	"github.com/gin-gonic/gin"
	"github.com/omec-project/openapi/v2"
	"github.com/omec-project/openapi/v2/models"
	"github.com/omec-project/openapi/v2/utils"
	smf_context "github.com/omec-project/smf/context"
	"github.com/omec-project/smf/fsm"
	"github.com/omec-project/smf/logger"
	stats "github.com/omec-project/smf/metrics"
	"github.com/omec-project/smf/msgtypes/svcmsgtypes"
	"github.com/omec-project/smf/transaction"
	smfutil "github.com/omec-project/smf/util"
	"github.com/omec-project/util/httpwrapper"
	mi "github.com/omec-project/util/metricinfo"
)

// Post /sm-contexts
// Create SM Context
func HTTPPostSmContexts(c *gin.Context) {
	logger.PduSessLog.Infoln("Handle Post /sm-contexts")
	var err error
	var request models.PostSmContextsRequest
	stats.IncrementN11MsgStats(smf_context.SMF_Self().NfInstanceID, string(svcmsgtypes.CreateSmContext), "In", "", "")
	err = stats.PublishMsgEvent(mi.Smf_msg_type_pdu_sess_create_req)
	if err != nil {
		logger.PduSessLog.Errorf("error: %v", err)
		return
	}

	request.SetJsonData(models.SmContextCreateData{})

	s := strings.Split(c.GetHeader("Content-Type"), ";")
	switch s[0] {
	case "application/json":
		err = c.ShouldBindJSON(request.JsonData)
	case "multipart/related", "multipart/form-data":
		err = c.ShouldBindWith(&request, openapi.MultipartRelatedBinding{})
	default:
		problemDetail := "[Request Body] unsupported Content-Type: " + c.GetHeader("Content-Type")
		rsp := utils.ProblemDetailsSystemFailure(problemDetail)
		stats.IncrementN11MsgStats(smf_context.SMF_Self().NfInstanceID, string(svcmsgtypes.CreateSmContext), "Out", http.StatusText(http.StatusUnsupportedMediaType), "UnsupportedMediaType")
		logger.PduSessLog.Errorln(problemDetail)
		c.JSON(http.StatusUnsupportedMediaType, rsp)
		return
	}
	defer smfutil.CleanupMultipartTempFiles(request)

	if err != nil {
		problemDetail := "[Request Body] " + err.Error()
		rsp := utils.ProblemDetailsMalformedRequestSyntax(problemDetail)
		stats.IncrementN11MsgStats(smf_context.SMF_Self().NfInstanceID, string(svcmsgtypes.CreateSmContext), "Out", http.StatusText(http.StatusBadRequest), "Malformed")
		logger.PduSessLog.Errorln(problemDetail)
		c.JSON(http.StatusBadRequest, rsp)
		return
	}

	req := httpwrapper.NewRequest(c.Request, request)
	txn := transaction.NewTransaction(req.Body.(models.PostSmContextsRequest), nil, svcmsgtypes.CreateSmContext)

	go txn.StartTxnLifeCycle(fsm.SmfTxnFsmHandle)
	<-txn.Status // wait for txn to complete at SMF
	HTTPResponse, ok := txn.Rsp.(*httpwrapper.Response)
	if !ok || HTTPResponse == nil {
		logger.PduSessLog.Errorf("create SM Context transaction finished without HTTP response: err=%v", txn.Err)
		HTTPResponse = &httpwrapper.Response{
			Header: nil,
			Status: http.StatusInternalServerError,
			Body: &models.ProblemDetails{
				Title:  openapi.PtrString("SMF transaction failure"),
				Status: openapi.PtrInt32(http.StatusInternalServerError),
				Detail: openapi.PtrString("create SM Context terminated before building an HTTP response"),
			},
		}
	}
	var smContext *smf_context.SMContext
	if txn.Ctxt != nil {
		smContext, _ = txn.Ctxt.(*smf_context.SMContext)
	}
	errStr := ""
	if txn.Err != nil {
		errStr = txn.Err.Error()
	}

	// Http Response to AMF
	for key, val := range HTTPResponse.Header {
		c.Header(key, val[0])
	}
	stats.IncrementN11MsgStats(smf_context.SMF_Self().NfInstanceID, string(svcmsgtypes.CreateSmContext), "Out", http.StatusText(HTTPResponse.Status), errStr)
	switch HTTPResponse.Status {
	case http.StatusCreated,
		http.StatusBadRequest,
		http.StatusForbidden,
		http.StatusNotFound,
		http.StatusInternalServerError,
		http.StatusServiceUnavailable,
		http.StatusGatewayTimeout:
		c.Render(HTTPResponse.Status, openapi.MultipartRelatedRender{Data: HTTPResponse.Body})
		smfutil.CleanupMultipartTempFiles(HTTPResponse.Body)
	default:
		c.JSON(HTTPResponse.Status, HTTPResponse.Body)
	}

	go func(smContext *smf_context.SMContext) {
		var txn *transaction.Transaction
		if smContext == nil {
			return
		}
		if HTTPResponse.Status == http.StatusCreated {
			txn = transaction.NewTransaction(nil, nil, svcmsgtypes.PfcpSessCreate)
			txn.Ctxt = smContext
			go txn.StartTxnLifeCycle(fsm.SmfTxnFsmHandle)
			<-txn.Status
		} else {
			smf_context.RemoveSMContext(smContext.Ref)
		}
	}(smContext)
}
