// Copyright (c) 2026 Intel Corporation
// SPDX-License-Identifier: Apache-2.0

/*
Nsmf_PDUSession

SMF PDU Session Service.
© 2024, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).
All rights reserved.

API version: 1.3.0-alpha.7

Authors: Aether SD-Core team
Contact: dev@lists.aetherproject.org

Generated by: OpenAPI Generator (https://openapi-generator.tech)
*/

package pdusession

import (
	"github.com/gin-gonic/gin"
	"github.com/omec-project/smf/logger"
)

// Post /pdu-sessions/:pduSessionRef/release
// Release
func HTTPReleasePduSession(c *gin.Context) {
	detail := "Handle Post /pdu-sessions/:pduSessionRef/release is not implemented"
	logger.PduSessLog.Warnln(detail)
	writeNotImplementedProblem(c, detail)
}

// Post /pdu-sessions/:pduSessionRef/retrieve
// Retrieve
func HTTPRetrievePduSession(c *gin.Context) {
	detail := "Handle Post /pdu-sessions/:pduSessionRef/retrieve is not implemented"
	logger.PduSessLog.Warnln(detail)
	writeNotImplementedProblem(c, detail)
}

// Post /pdu-sessions/:pduSessionRef/transfer-mo-data
// Transfer MO Data
func HTTPTransferMoData(c *gin.Context) {
	detail := "Handle Post /pdu-sessions/:pduSessionRef/transfer-mo-data is not implemented"
	logger.PduSessLog.Warnln(detail)
	writeNotImplementedProblem(c, detail)
}

// Post /pdu-sessions/:pduSessionRef/modify
// Update (initiated by V-SMF or I-SMF)
func HTTPUpdatePduSession(c *gin.Context) {
	detail := "Handle Post /pdu-sessions/:pduSessionRef/modify is not implemented"
	logger.PduSessLog.Warnln(detail)
	writeNotImplementedProblem(c, detail)
}
