// SPDX-FileCopyrightText: 2025 Intel Corporation
// SPDX-License-Identifier: Apache-2.0

/*
Nsmf_PDUSession

SMF PDU Session Service.
© 2024, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).
All rights reserved.

API version: 1.3.0-alpha.7

Authors: Aether SD-Core team
Contact: dev@lists.aetherproject.org

Generated by: OpenAPI Generator (https://openapi-generator.tech)
*/

package oam

import (
	"net/http"

	"github.com/gin-gonic/gin"
	"github.com/omec-project/openapi/v2/models"
)

// Route is the information for every URI.
type Route struct {
	// Name is the name of this Route.
	Name string
	// Method is the string for the HTTP method (e.g., GET, POST, etc.)
	Method string
	// Pattern is the pattern of the URI.
	Pattern string
	// HandlerFunc is the handler function of this route.
	HandlerFunc gin.HandlerFunc
}

// AddService adds routes to an existing gin engine.
func AddService(engine *gin.Engine) *gin.RouterGroup {
	group := engine.Group("/nsmf-oam/v1")
	for _, route := range getRoutes() {
		if route.HandlerFunc == nil {
			route.HandlerFunc = DefaultHandleFunc
		}
		switch route.Method {
		case http.MethodGet:
			group.GET(route.Pattern, route.HandlerFunc)
		case http.MethodOptions:
			group.OPTIONS(route.Pattern, route.HandlerFunc)
		}
	}

	return group
}

// Default handler for not yet implemented routes
func DefaultHandleFunc(c *gin.Context) {
	writeNotImplementedProblem(c, "This API route is not implemented")
}

func writeNotImplementedProblem(c *gin.Context, detail string) {
	problemDetails := models.NewProblemDetails()
	problemDetails.SetStatus(http.StatusNotImplemented)
	problemDetails.SetCause("NOT_IMPLEMENTED")
	problemDetails.SetDetail(detail)
	c.JSON(http.StatusNotImplemented, problemDetails)
}

func getRoutes() []Route {
	return []Route{
		{
			"Get UE PDU Session Info",
			"GET",
			"/ue-pdu-session-info/:smContextRef",
			GetUePduSessionInfo,
		},
	}
}
