# SPDX-License-Identifier: Apache-2.0
# SPDX-FileCopyrightText: 2024 Canonical Ltd.

info:
  version: 1.0.0
  description: SMF initial local configuration

configuration:
  enableDBStore: false
  enableUPFAdapter: true
  debugProfilePort: 5001
  smfName: SMF # the name of this SMF
  nrfUri: http://nrf:29510 # a valid URI of NRF
  webuiUri: myspecialwebui:9872 # a valid URI of Webui

