# SPDX-FileCopyrightText: 2021 Open Networking Foundation <info@opennetworking.org>
#
# SPDX-License-Identifier: Apache-2.0
# SPDX-License-Identifier: LicenseRef-ONF-Member-Only-1.0

info:
  version: 1.0.0
  description: Routing information for UE

ueRoutingInfo: # the list of UE routing information
  - SUPI: imsi-2089300007487 # Subscription Permanent Identifier of the UE
    AN: 198.18.0.2 # the IP address of RAN
    PathList: # the pre-config paths for this SUPI
      - DestinationIP: 60.60.0.101 # the destination IP address on Data Network (DN)
        # the order of UPF nodes in this path. We use the UPF's name to represent each UPF node.
        # The UPF's name should be consistent with smfcfg.yaml
        UPF: !!seq
          - BranchingUPF
          - AnchorUPF1

      - DestinationIP: 60.60.0.102 # the destination IP address on Data Network (DN)
        # the order of UPF nodes in this path. We use the UPF's name to represent each UPF node.
        # The UPF's name should be consistent with smfcfg.yaml
        UPF: !!seq
          - BranchingUPF
          - AnchorUPF2
routeProfile:
  MEC1:
    forwardingPolicyID: 10
  MEC2:
    forwardingPolicyID: 10

pfdDataForApp:
  - applicationId: "1000"
    pfds:
      - pfdID: pfd1
        flowDescriptions:
          - permit out ip from any to 60.60.0.102 2000
          - permit in ip from 60.60.0.102 2000 to any
