// Copyright (c) 2026 Intel Corporation
// SPDX-License-Identifier: Apache-2.0

/*
Nsmf_EventExposure

Session Management Event Exposure Service.
© 2024, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).
All rights reserved.

API version: 1.3.0-alpha.6

Authors: Aether SD-Core team
Contact: dev@lists.aetherproject.org

Generated by: OpenAPI Generator (https://openapi-generator.tech)
*/

package eventexposure

import (
	"net/http"

	"github.com/gin-gonic/gin"
	"github.com/omec-project/smf/logger"
)

// Delete /subscriptions/:subId
// Delete an individual subscription for event notifications from the SMF
func HTTPDeleteIndividualSubcription(c *gin.Context) {
	logger.EventExposureLog.Warnln("Handle Delete /subscriptions/:subId is not implemented")
	c.String(http.StatusNotImplemented, "501 not implemented")
}

// Get /subscriptions/:subId
// Read an individual subscription for event notifications from the SMF
func HTTPGetIndividualSubcription(c *gin.Context) {
	logger.EventExposureLog.Warnln("Handle Get /subscriptions/:subId is not implemented")
	c.String(http.StatusNotImplemented, "501 not implemented")
}

// Put /subscriptions/:subId
// Replace an individual subscription for event notifications from the SMF
func HTTPReplaceIndividualSubcription(c *gin.Context) {
	logger.EventExposureLog.Warnln("Handle Put /subscriptions/:subId is not implemented")
	c.String(http.StatusNotImplemented, "501 not implemented")
}
