// Copyright (c) 2026 Intel Corporation
// SPDX-License-Identifier: Apache-2.0

/*
Nsmf_EventExposure

Session Management Event Exposure Service.
© 2024, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).
All rights reserved.

API version: 1.3.0-alpha.6

Authors: Aether SD-Core team
Contact: dev@lists.aetherproject.org

Generated by: OpenAPI Generator (https://openapi-generator.tech)
*/

package eventexposure

import (
	"github.com/gin-gonic/gin"
	"github.com/omec-project/smf/logger"
)

// Delete /subscriptions/:subId
// Delete an individual subscription for event notifications from the SMF
func HTTPDeleteIndividualSubscription(c *gin.Context) {
	detail := "Handle Delete /subscriptions/:subId is not implemented"
	logger.EventExposureLog.Warnln(detail)
	writeNotImplementedProblem(c, detail)
}

// Get /subscriptions/:subId
// Read an individual subscription for event notifications from the SMF
func HTTPGetIndividualSubscription(c *gin.Context) {
	detail := "Handle Get /subscriptions/:subId is not implemented"
	logger.EventExposureLog.Warnln(detail)
	writeNotImplementedProblem(c, detail)
}

// Put /subscriptions/:subId
// Replace an individual subscription for event notifications from the SMF
func HTTPReplaceIndividualSubscription(c *gin.Context) {
	detail := "Handle Put /subscriptions/:subId is not implemented"
	logger.EventExposureLog.Warnln(detail)
	writeNotImplementedProblem(c, detail)
}
